stages:
  prepare:
    cmd: python data/load_data.py
    outs:
      - data/housing.csv
  train:
    cmd: python src/train.py
    deps: 
      - data/housing.csv
    outs:
      - models/linear_model.pkl