name: House Price Prediction CI

on:
  push:
    branches:
      - main

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to handle rebase/merge

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install dvc mlflow scikit-learn pandas numpy joblib

      - name: Run DVC pipeline
        run: |
          dvc repro

      - name: Commit DVC lock changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add dvc.lock
          git commit -m "Update dvc.lock from CI" || echo "No changes to commit"
          git fetch origin main  # Fetch remote changes
          git merge --ff-only origin/main  # Fast-forward only if possible
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true  # Allow workflow to continue if merge fails